{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nexus.fullname" . }}-redis
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "nexus.fullname" . }}-redis
  replicas: 1
  selector:
    matchLabels:
      {{- include "nexus.selectorLabels" . | nindent 6 }}
      component: redis
  template:
    metadata:
      labels:
        {{- include "nexus.selectorLabels" . | nindent 8 }}
        component: redis
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        fsGroup: 999
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          args: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]
          ports:
            - name: redis
              containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.existingSecret }}
                  key: redis-password
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          readinessProbe:
            exec:
              command: ["sh", "-c", "redis-cli -a \"$REDIS_PASSWORD\" ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["sh", "-c", "redis-cli -a \"$REDIS_PASSWORD\" ping"]
            initialDelaySeconds: 15
            periodSeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.redis.storageClass }}
        storageClassName: {{ .Values.redis.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" . }}-redis
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 6379
      name: redis
  selector:
    {{- include "nexus.selectorLabels" . | nindent 4 }}
    component: redis
{{- end }}
