server.port=8080
server.servlet.context-path=/api/v1

spring.datasource.url=jdbc:postgresql://localhost:5433/nexus_oms
spring.datasource.username=nexus
spring.datasource.password=nexus_secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cache.type=redis
spring.cache.redis.time-to-live=5m
spring.cache.redis.cache-null-values=false
spring.cache.redis.use-key-prefix=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=nexus-oms-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

app.jwt.secret=NexusShipOMSSuperSecretKeyForJWTTokenGeneration2024!
app.jwt.expiration-ms=86400000

nexus.ai.base-url-ops=http://localhost:5000
nexus.ai.base-url-intel=http://localhost:5001

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

logging.file.path=logs
logging.file.name=logs/spring.log
logging.level.com.nexus.oms=DEBUG
logging.level.org.springframework.security=INFO

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
